import Head from 'next/head';
import Products from '../components/Products';
import Sidebar from '../components/Sidebar';

const Home = ({ products }) => {
  return (
    <div>
      <Head>
        <title>
          Holland & Barrett - The UK&apos;s Leading Health & Wellbeing Store
        </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='text-sm my-6 mx-24'>
        <p>
          <span className='text-hbgreen mr-4 hover:underline cursor-pointer'>
            Home
          </span>{' '}
          <span className='text-xl mr-2'>{'>'}</span> Protein Powder for £30 or
          Less
        </p>
      </div>
      <div className='flex justify-center text-3xl font-semibold'>
        <h1>Protein Powder for £30 or Less</h1>
      </div>
      {/* Content */}
      <div className='grid grid-cols-5 gap-2 m-8'>
        <Sidebar />
        <Products products={products} />
      </div>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const res = await fetch('http://localhost:3000/products');
  const products = await res.json();

  return { props: { products } };
}
